//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.16 at 12:08:57 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.examples.com/wsdl/HelloService.wsdl", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package https.www_howtodoinjava_com.xml.school;
